version: '3.8'


# ADD ENV VARS INSTEAD OF STATIC VARS 
# FOR FINAL RELEASE
# 
# ADJUST PORTS 

services: 
  db: 
    image: postgres:16
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydbname
      # change these eventually 
    ports: 
      - "5432:5432"
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
  pgadmin: 
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=placeholder@placeholder.com
      - PGADMIN_DEFAULT_PASSWORD=changeme
    ports: 
      - "1234:80"
    volumes: 
      - ./pgadmin-data:/var/lib/pgadmin

  # minio goes here
      #
      #
      #

  # searxng goes here
      #
      #
      #
