version: '28.1.1'

services: 

  searxng: 
    image: docker.io/searxng/searxng:latest
    ports: 
      - "8888:8080"
    volumes:
      - ./config/:/etc/searxng/
      - ./data/:/var/cache/searxng/
    
